Bump up max_tokens_here limit for base/feature_list.cc
On MacOS:

In file included from ../../brave/chromium_src/base/featur./../../src/basee_list.cc:88:
 ./feature_list.cc:11:31: error: the number of preprocessor source tokens (600165) exceeds this token limit (600000) [-Werror,-Wmax-tokens]
 #pragma clang max_tokens_here 600000
                               ^
 1 error generated.

Chromium already bumped to 610000, but it's not in cr105 yet.

https://source.chromium.org/chromium/chromium/src/+/dcca26f5109ebb79e0c209e6c6a187cd202b945a